on:
  push:
    branches:
      - main
    paths:
      - flatpak/**
  workflow_dispatch:

name: CI
jobs:
  flatpak-builder:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: fedora:latest
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v4
      - name: Install Flatpak Builder and Flatpak
        run: |
          dnf -y install flatpak-builder flatpak
      - name: Install QEMU deps
        if: ${{ matrix.arch != 'x86_64' }}
        run: |
          dnf -y install docker
      - name: Set up QEMU
        if: ${{ matrix.arch != 'x86_64' }}
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Find version
        run: |
          dnf -y install jq
          echo "RELEASE_TAG=$(jq -r '.version' package.json)" >> $GITHUB_ENV
      - name: Set output filename
        run: echo "ARTIFACT_FILENAME=MessengerGnome-${{ matrix.arch }}-${{ env.RELEASE_TAG }}.flatpak" >> $GITHUB_ENV
      - name: Build flatpak
        run: |
          cd flatpak
          /bin/env flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          /bin/env flatpak-builder build/ com.haryp.MessengerGnome.yml --install-deps-from=flathub --arch=${{ matrix.arch }}
          /bin/env flatpak build-export export build
          /bin/env flatpak build-bundle --arch=${{ matrix.arch }} export ${{ env.ARTIFACT_FILENAME }} com.haryp.MessengerGnome
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "flatpak/${{ env.ARTIFACT_FILENAME }}"
          tag: ${{ env.RELEASE_TAG }}
          allowUpdates: true
